# Generated by Django 6.0 on 2025-12-26 15:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_units', models.PositiveSmallIntegerField(default=12)),
                ('max_units', models.PositiveSmallIntegerField(default=24)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-semester__year', '-semester__term'],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('status', models.CharField(choices=[('enrolled', 'در حال گذراندن'), ('passed', 'قبول شده'), ('failed', 'مردود شده'), ('dropped', 'حذف شده'), ('incomplete', 'ناتمام'), ('withdrawn', 'انصراف داده شده')], default='enrolled', max_length=20)),
                ('enrollment_date', models.DateTimeField(auto_now_add=True)),
                ('grade_date', models.DateTimeField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering')),
                ('student_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentsemester')),
            ],
            options={
                'verbose_name': 'درس دانشجو',
                'verbose_name_plural': 'StudentCourse',
                'ordering': ['enrollment_date'],
                'unique_together': {('student_semester', 'course_offering')},
            },
        ),
    ]
