# Generated by Django 6.0 on 2025-12-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professor', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='course name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='course code')),
                ('capacity', models.PositiveIntegerField(verbose_name='capacity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_for', to='courses.course')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Professor.professor', verbose_name='professor')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday')], max_length=10, verbose_name='day of week')),
                ('time_slot', models.CharField(choices=[('8-10', '8:00 - 10:00'), ('10-12', '10:00 - 12:00'), ('14-16', '14:00 - 16:00'), ('16-18', '16:00 - 18:00')], max_length=10, verbose_name='time slot')),
                ('location', models.CharField(max_length=50, verbose_name='location')),
                ('semester', models.CharField(max_length=10, verbose_name='semester')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course schedule',
                'verbose_name_plural': 'course schedules',
                'unique_together': {('course', 'day_of_week', 'time_slot')},
            },
        ),
    ]
